name: Commit Message Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  commit-message-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check commit messages
        run: |
          PREFIX="[GIT-"

          # Determine the common ancestor (merge base) of the base branch and the current branch
          BASE_COMMIT=$(git merge-base ${{ github.event.pull_request.base.sha }} HEAD)

          # Get all commit messages between the base commit and the current HEAD
          COMMITS=$(git log $BASE_COMMIT..HEAD --pretty=format:"%s")

          echo "Commit messages found: $COMMITS"

          for COMMIT in $COMMITS; do
            if [[ "$COMMIT" != "$PREFIX"* ]]; then
              echo "Error: Commit message '$COMMIT' does not start with '$PREFIX'."
              exit 1
            fi
          done