name: Commit Message Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  commit-message-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check commit messages
        run: |
          PREFIX="[GIT-"  # Replace with your desired prefix

          # Get the commit range from the base branch to the current HEAD
          COMMITS=$(git log ${{ github.event.pull_request.base.sha }}..${{ github.sha }} --pretty=format:"%s")

          echo "Commit messages found: $COMMITS"

          for COMMIT in $COMMITS; do
            if [[ "$COMMIT" != "$PREFIX"* ]]; then
              echo "Error: Commit message '$COMMIT' does not start with '$PREFIX'."
              exit 1
            fi
          done